@startuml CasosDeUso
left to right direction
actor Jogador as J
actor "dono de quadra" as D
package System{
    usecase "Editar time" as UC1
    usecase "Marcar amistoso" as UC2
    usecase "Agendar partida" as UC3
    usecase "Criar time" as UC4
    usecase "Adicionar Jogadores ao time" as UC5
    usecase "Solicitar entrar em time" as UC6
    usecase "Entrar em time" as UC7
    usecase "Definir escalamento de time" as UC8
    usecase "Marcar campeonato" as UC9
    usecase "Disponibilizar quadra" as UC10
    usecase "Editar campeonato" as UC11
}

J -- UC1
J -- UC2
J -- UC3
J -- UC4
J -- UC5
J -- UC6
UC6 .> UC7 : <extends>
J -- UC8

D -- UC9
D -- UC10
D -- UC11

@enduml